server:
  port: 9091

spring:
  main:
    # SpringBoot 구동시 Bean이 중복선언되는 경우 오류가 발생하는 경우 
    # 중복 생성 허용 가능 하도록 하는 옵션
    allow-bean-definition-overriding: true
    
  output:
    # Console Color 표시
    ansi:
      enabled: ALWAYS
      
  datasource:
    mysqlds:
      maximum-pool-size: 4
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/roopy?allowPublicKeyRetrieval=true&useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&useSSL=false
      username: root
      password: admin1234
    pgsqlds:
      maximum-pool-size: 4
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: admin !@34
logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    com.roopy: DEBUG     
      
      